on:
  push:
  pull_request:

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install Curl
        run: sudo apt install libcurl4-openssl-dev libssl-dev
      - name: Restore renv snapshot
        shell: Rscript {0}
        run: |
          if (!require('renv')) install.packages('renv')
          renv::restore()
      - name: Push to shiny.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='username', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appName = 'appname')"